### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by Yazan-Ali-01** [DeanShooster/NodeJS-BookStore#1]
Hey 
I was wondering 
how to make the first admin ???

**Comment by DeanShooster** [comment]
Hello,

First Admin should be made by a temporarily route that you make and should remove afterwards.

Example:

router.post('/create-admin',async(req,res)=>{
   const newAdmin = new Admin(req.admin);
   await newAdmin.save();
   res.send(newAdmin);
})

**Comment by Yazan-Ali-01** [comment]
What if I want the main page to be also an admin page ?

**Comment by Yazan-Ali-01** [comment]
Ok, thanks for the clarification.
